version: '3.5'

services:
  server:
    build: .
    container_name: server
    volumes:
      - "./:/usr/src"
    networks:
      - some-net
    working_dir: /usr/src/
    command: "python sleep.py"
    
networks:
  some-net:
    name: custom_network